import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const args=process.argv.slice(2),option=(key,fallback)=>args.includes(key)?args[args.indexOf(key)+1]:fallback;
const {chromium}=createRequire(import.meta.url)(option('--playwright',process.env.HAQI_PLAYWRIGHT_PACKAGE||'playwright'));
const output=path.resolve(option('--output','.cache/island-performance'));fs.mkdirSync(output,{recursive:true});
const digest=createHash('sha256');for(const file of fs.readdirSync('js').filter(file=>file.endsWith('.js')).sort())digest.update(file).update(fs.readFileSync(path.join('js',file)));
const browser=await chromium.launch({headless:!args.includes('--headed'),channel:option('--channel','msedge')}),report={browser:await browser.version(),channel:option('--channel','msedge'),headed:args.includes('--headed'),sourceHash:digest.digest('hex'),dpr:Number(option('--dpr','1')),seconds:Number(option('--seconds','15')),main:args.includes('--main'),assets:option('--assets','cdn'),rows:[],errors:[]};
try{for(const zone of option('--zones',option('--zone','ice')).split(','))for(const width of option('--widths','1280,390').split(',').map(Number)){
 const context=await browser.newContext({viewport:{width,height:900},deviceScaleFactor:Number(option('--dpr','1'))}),page=await context.newPage();page.on('pageerror',e=>{report.errors.push(e.stack);console.error(e.stack);});
 if(args.includes('--baseline')){const prefix=execFileSync('git',['rev-parse','--show-prefix'],{encoding:'utf8'}).trim();for(const file of ['adventure_renderer.js','terrain_tile_scheduler.js','adventure_pet_scene.js']){const body=execFileSync('git',['show',`HEAD:${prefix}js/${file}`],{encoding:'utf8'});await page.route(`**/js/${file}*`,route=>route.fulfill({contentType:'application/javascript',body}));}}
 if(args.includes('--main'))await page.route('**/js/adventure_app.js*',async route=>{const response=await route.fetch();let source=await response.text();source+=`\nwindow.islandQA={ready:()=>stage==='title'&&!!assets,async create(){const next=A.createAdventure(assets.content,{name:'性能验收',school:'fire',seed:731});next.xp=assets.content.progression.xpThresholds[49];next.level=50;next.zone=new URLSearchParams(location.search).get('zone')||'ice';const layout=assets.content.worldMaps[next.zone],region=layout.regions.find(r=>r.name==='西部松林');next.position=region?{x:region.x,y:region.y}:{...layout.spawn};next.languageLearning={...next.languageLearning,native:'zh-CN',target:'en',selectionConfirmed:true};await activateRole(roleStore.create(next));close();await assets.warmScenery(world);await assets.warmNearby(world,save);},async sample(seconds,walk=false){close();const frames=[],draws=[];let last=null;const original=renderer.render;renderer.render=function(...args){const start=performance.now();const result=original.apply(this,args);draws.push(performance.now()-start);return result;};const start={...save.position};let travelled=0,prior=start;const until=performance.now()+seconds*1000;try{await new Promise(resolve=>{function tick(t){if(last!==null)frames.push(t-last);last=t;travelled+=W.distance(prior,save.position);prior={...save.position};if(walk){const sign=Math.floor((until-t)/2000)%2?1:-1;joystick={x:sign,y:sign*.5};}if(t>=until)resolve();else requestAnimationFrame(tick);}requestAnimationFrame(tick);});}finally{joystick={x:0,y:0};renderer.render=original;}const metric=rows=>{const s=[...rows].sort((a,b)=>a-b);return{count:s.length,mean:s.reduce((n,v)=>n+v,0)/s.length,p95:s[Math.floor(s.length*.95)],p99:s[Math.floor(s.length*.99)],max:s.at(-1),over25:s.filter(v=>v>25).length};};return{frame:metric(frames),draw:metric(draws),start,end:{...save.position},travelled,stage,trees:world.trees.length,cache:renderer.terrainStats()};}};`;await route.fulfill({response,body:source});});
 await page.goto(option('--url','http://127.0.0.1:8797')+(args.includes('--main')?'/Haqi.html':'/tests/fixtures/island-performance.html')+'?assets='+option('--assets','cdn')+'&zone='+zone);
 await page.waitForFunction(()=>window.islandQA,null,{timeout:120000});await page.waitForTimeout(4000);
 if(args.includes('--main')){await page.waitForFunction(()=>islandQA.ready());await page.evaluate(()=>islandQA.create());await page.waitForTimeout(4000);}
 if(args.includes('--cpu')){const cdp=await context.newCDPSession(page);await cdp.send('Profiler.enable');await cdp.send('Profiler.start');page._islandCdp=cdp;}
 for(const moving of [false,true]){const row={zone,width,moving,...await page.evaluate(({seconds,moving})=>islandQA.sample(seconds,moving),{seconds:Number(option('--seconds','15')),moving})};report.rows.push(row);console.log(JSON.stringify(row));}
 if(page._islandCdp){const {profile}=await page._islandCdp.send('Profiler.stop');fs.writeFileSync(path.join(output,`cpu-${zone}-${width}.json`),JSON.stringify(profile));}
 await page.screenshot({path:path.join(output,`scene-${zone}-${width}.png`)});await context.close();
}fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));if(report.errors.length)throw Error(report.errors.join('\n'));}finally{await browser.close();}
