import {createRequire} from 'node:module';
import fs from 'node:fs';
const args=process.argv.slice(2),option=(key,fallback)=>args.includes(key)?args[args.indexOf(key)+1]:fallback;
const {chromium}=createRequire(import.meta.url)(option('--playwright',process.env.HAQI_PLAYWRIGHT_PACKAGE||'playwright'));
const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1280,height:900}});
try{await page.goto(option('--url','http://127.0.0.1:8798')+'/tests/fixtures/island-performance.html?assets=cdn');await page.waitForFunction(()=>window.islandQA,null,{timeout:120000});
const result=await page.evaluate(async()=>{
 const q=islandQA,{paintLargeTerrain}=await import('../../js/adventure_large_terrain.js'),{createIslandTerrainRasterizer}=await import('../../js/island_terrain_rasterizer.js'),{createIslandSceneryCache}=await import('../../js/island_scenery_cache.js'),rows=[];
 const raster=createIslandTerrainRasterizer(q.assets.terrainDecorationArt);
 const originalImages={...q.assets.terrainDecorationArt.images},bitmapImages=Object.fromEntries(await Promise.all(Object.entries(originalImages).map(async([key,image])=>[key,await createImageBitmap(image)])));
 const bitmapArt={draw(c,atlas,name,x,y,w,h){const crop=q.assets.terrainDecorationArt.manifest.atlases[atlas]?.frames[name]?.rect,image=bitmapImages[atlas];if(!crop||!image)return false;const ratio=Math.min(w/crop[2],h/crop[3]),dw=crop[2]*ratio,dh=crop[3]*ratio;c.drawImage(image,...crop,x+(w-dw)/2,y+h-dh,dw,dh);return true;}};
 const diff=(a,b)=>{let changed=0,max=0,total=0;for(let i=0;i<a.length;i++){const d=Math.abs(a[i]-b[i]);changed+=Number(d>0);max=Math.max(max,d);total+=d;}return{changed,max,mean:total/a.length};};
 for(const scale of [1,2])for(const [x,y] of [[1024,2560],[1536,2560],[2048,3072]]){const pixels=512*scale+4,margin=2/scale,rect={x:x-margin,y:y-margin,w:512+margin*2,h:512+margin*2},canvas=new OffscreenCanvas(pixels,pixels),dom=document.createElement('canvas');dom.width=dom.height=pixels;const c=canvas.getContext('2d',{willReadFrequently:true}),d=dom.getContext('2d',{willReadFrequently:true});for(const ctx of [c,d]){ctx.scale(scale,scale);ctx.translate(-rect.x,-rect.y);}paintLargeTerrain(c,q.world,rect,false,bitmapArt);paintLargeTerrain(d,q.world,rect,false,q.assets.terrainDecorationArt);const expected=c.getImageData(0,0,pixels,pixels).data,legacy=d.getImageData(0,0,pixels,pixels).data,result=await raster(q.world,rect,pixels,scale);c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,pixels,pixels);c.drawImage(result.bitmap,0,0);result.bitmap.close();const actual=c.getImageData(0,0,pixels,pixels).data;rows.push({kind:'terrain',scale,x,y,...diff(expected,actual),legacyHtmlCanvas:diff(legacy,actual)});}
 const objects=q.world.trees.filter(o=>!o.snow&&o.x>1000&&o.x<1600&&o.y>2500&&o.y<2800).slice(0,4).map(o=>({...o,kind:'tree'})).sort((a,b)=>a.y-b.y);
 const paint=(c,o)=>{q.assets.tile(c,'sprites',o.tile,o.x-o.size/2,o.y-o.size+10,o.size,o.size);const size=o.size*.36,variant=Math.abs(Math.round(o.x*7+o.y*13))%8;q.assets.sceneryTile(c,8+variant,o.x+o.size*.18,o.y-size+14,size,size);};
 for(const scale of [1,2]){const a=document.createElement('canvas'),b=document.createElement('canvas');a.width=b.width=800*scale;a.height=b.height=600*scale;const ca=a.getContext('2d',{willReadFrequently:true}),cb=b.getContext('2d',{willReadFrequently:true});for(const c of [ca,cb]){c.fillStyle='#638765';c.fillRect(0,0,a.width,a.height);c.scale(scale,scale);c.translate(-900,-2300);}for(const o of objects)paint(ca,o);const tasks=[],cache=createIslandSceneryCache({paint,schedule:fn=>{tasks.push(fn);return fn;},cancel:()=>{}});cache.begin(q.world,{},scale);const hero={x:4000,y:4000},rect={x:900,y:2300,w:800,h:600};for(let i=0;i<objects.length;i++)cache.draw(cb,objects,i,hero,rect);while(tasks.length)tasks.shift()();for(let i=0;i<objects.length;){const end=cache.draw(cb,objects,i,hero,rect);if(end>i)i=end;else paint(cb,objects[i++]);}rows.push({kind:'scenery',scale,objects:objects.length,...diff(ca.getImageData(0,0,a.width,a.height).data,cb.getImageData(0,0,b.width,b.height).data)});cache.clear();}
 const {createIslandCompanionNavigation}=await import('../../js/island_companion_navigation.js'),{findPath,clearSegment}=await import('../../js/adventure_world_core.js');
 const world={...q.world,trees:[],paths:[],npcs:[],encounters:[],buildings:[{x:1490,y:2850,w:160,h:160}]},from={x:1370,y:2840},to={x:1610,y:2840},actor={position:{...from},path:[]};if(clearSegment(world,from,to))throw Error('Path fixture does not block direct movement');
 const {findPetMeeting,petMeetingPath}=await import('../../js/adventure_pet_meeting_core.js'),navigation=createIslandCompanionNavigation();
 for(const meetingPath of [false,true]){const expectedPath=meetingPath?petMeetingPath(world,from,to):findPath(world,from,to);actor.path=[];navigation.options(actor,world,()=>true,meetingPath).requestPath(from,to);const deadline=performance.now()+10000;while(navigation.stats().pending&&performance.now()<deadline)await new Promise(r=>setTimeout(r,5));rows.push({kind:'navigation',meetingPath,equal:JSON.stringify(expectedPath)===JSON.stringify(actor.path),points:actor.path.length,failed:navigation.stats().failed});}
 const participants=[from,to],expectedAnchor=findPetMeeting(world,participants,[],q.assets.content),anchor=await navigation.findMeeting(world,participants,[],q.assets.content);rows.push({kind:'navigation',meeting:true,equal:JSON.stringify(expectedAnchor)===JSON.stringify(anchor),points:anchor?1:0,failed:navigation.stats().failed});navigation.dispose();for(const image of Object.values(bitmapImages))image.close();
 return rows;
});fs.mkdirSync('.cache/island-parity',{recursive:true});fs.writeFileSync('.cache/island-parity/report.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(result.some(row=>row.kind==='terrain'?row.max!==0:row.kind==='navigation'?!row.equal||row.failed||!row.points:row.max>4))throw Error('Island rendering/path comparison failed');}finally{await browser.close();}
