// Isolated browser acceptance. Real image processing; mock account/provider/CDN.
import {createRequire} from 'node:module';
import fs from 'node:fs';
const args=process.argv.slice(2),option=(key,fallback)=>args.includes(key)?args[args.indexOf(key)+1]:fallback;
const {chromium}=createRequire(import.meta.url)(option('--playwright','playwright'));
const url=option('--url','http://127.0.0.1:8797'),output=option('--output','.cache/photo-head-qa');fs.mkdirSync(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'}),report={rows:[],errors:[]};
try{
 for(const viewport of [{width:1280,height:900},{width:390,height:844}]){
  const context=await browser.newContext({viewport}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
  const reference=JSON.parse(fs.readFileSync('data/adventure/hero-art.json')).heads['elf-boy'];
  await page.route(reference.cdn,route=>route.fulfill({status:200,headers:{'access-control-allow-origin':'*','content-type':'image/webp'},body:fs.readFileSync(reference.local)}));
  await page.route('https://cdn.keepwork.com/users/photoqa/**',async route=>{
   const data=await page.evaluate(url=>photoQA.uploads[url],route.request().url());
   await route.fulfill({status:data?200:404,headers:{'access-control-allow-origin':'*','content-type':'image/webp'},body:data?Buffer.from(data.split(',')[1],'base64'):Buffer.alloc(0)});
  });
  await page.goto(url+'/tests/fixtures/photo-head.html?assets=local&holdUpload');await page.waitForFunction(()=>document.documentElement.dataset.fixtureReady==='1'||document.documentElement.dataset.fixtureError,null,{timeout:90000});
  const fixtureError=await page.evaluate(()=>document.documentElement.dataset.fixtureError);if(fixtureError)throw Error(fixtureError);
  console.log(`照片形象 ${viewport.width}px：开始裁剪与生成验收`);
  await page.getByRole('button',{name:'打开照片形象',exact:true}).click();await page.getByText('免费体验1次',{exact:true}).waitFor();
  await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('fixture denied','NotAllowedError');};});
  await page.getByRole('button',{name:'拍摄照片',exact:true}).click();await page.getByText('无法打开摄像头，请允许相机权限或上传照片。',{exact:true}).waitFor();
  await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle='#e3b68a';ctx.fillRect(0,0,128,128);const stream=canvas.captureStream(2);for(const track of stream.getTracks()){const stop=track.stop.bind(track);track.stop=()=>{photoQA.cameraStops++;stop();};}return stream;};});
  await page.getByRole('button',{name:'拍摄照片',exact:true}).click();await page.locator('video').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('video').videoWidth>0);
  await page.getByRole('button',{name:'拍下照片',exact:true}).click();if(!await page.evaluate(()=>photoQA.cameraStops===1))throw Error('Camera was not stopped');
  await page.locator('input[type=file]').setInputFiles('assets/hero-preview/head-elf-boy.webp');await page.locator('.photo-head-crop').waitFor({state:'visible'});
  const cropBox=await page.locator('.photo-head-crop').boundingBox(),cx=cropBox.x+cropBox.width/2,cy=cropBox.y+cropBox.height/2;
  const zoomInput=page.getByLabel('缩放',{exact:true});
  await page.mouse.move(cx,cy);await page.mouse.wheel(0,-160);await page.waitForFunction(()=>Number(document.querySelector('.photo-head-editor input[type=range]').value)>1);
  const wheelZoom=Number(await zoomInput.inputValue());await page.mouse.wheel(0,160);await page.waitForFunction(v=>Number(document.querySelector('.photo-head-editor input[type=range]').value)<v,wheelZoom);
  await page.getByRole('button',{name:'重置',exact:true}).click();
  // Real browser touch events exercise pointer capture and two-finger transitions.
  const touch=await context.newCDPSession(page),points=spread=>[{x:cx-spread,y:cy,id:1},{x:cx+spread,y:cy,id:2}];
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points(25)});
  await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points(50)});
  if(Number(await zoomInput.inputValue())<1.8)throw Error('Pinch did not zoom in');
  await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points(200)});
  await page.waitForFunction(()=>Number(document.querySelector('.photo-head-editor input[type=range]').value)===3);
  await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points(8)});
  await page.waitForFunction(()=>Number(document.querySelector('.photo-head-editor input[type=range]').value)===1);
  await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points(200)});
  await page.waitForFunction(()=>Number(document.querySelector('.photo-head-editor input[type=range]').value)===3);
  await touch.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx,y:cy,id:3}]});
  await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx+12,y:cy+8,id:3}]});
  if(Number(await zoomInput.inputValue())!==3)throw Error('One-finger drag changed zoom after pinch cancel');
  await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touch.detach();
  await page.getByRole('button',{name:'旋转90°',exact:true}).click();await page.getByRole('button',{name:'重置',exact:true}).click();
  await page.screenshot({path:output+'/'+viewport.width+'-crop.png'});
  await page.getByRole('button',{name:'下一步：变身',exact:true}).click();
  await page.waitForFunction(()=>!!photoQA.releaseUpload);
  if(await page.locator('.photo-head-dialog progress').evaluate(n=>n.hidden||n.value!==50))throw Error('Upload progress was not shown');
  await page.screenshot({path:`${output}/${viewport.width}-uploading.png`});await page.evaluate(()=>photoQA.releaseUpload());
  await page.getByText('拖动头部，调整与身体的位置',{exact:true}).waitFor({timeout:90000});
  const zoomBefore=await zoomInput.inputValue();
  await page.getByRole('button',{name:'选照片',exact:true}).click();await page.locator('.photo-head-crop').waitFor({state:'visible'});
  if(await zoomInput.inputValue()!==zoomBefore)throw Error('Step navigation reset the crop');
  if(!await page.getByRole('button',{name:'变身',exact:true}).isDisabled())throw Error('Completed process step should not restart generation');
  await page.getByRole('button',{name:'校准',exact:true}).click();
  if(await page.evaluate(()=>photoQA.generationCalls)!==1)throw Error('Step navigation regenerated an avatar');
  const beforeNeck=await page.evaluate(()=>photoQA.service.state.head.frames[0].neck[0]);
  await page.getByRole('button',{name:'朝前',exact:true}).click();
  if(await page.getByRole('button',{name:'水平镜像',exact:true}).count()||await page.getByRole('button',{name:'逐帧精调',exact:true}).count())throw Error('Retired calibration tools still visible');
  for(let i=0;i<4;i++)await page.getByRole('button',{name:i===3?'完成四向校准':'校准，下一个',exact:true}).click();
    await page.waitForFunction(()=>!photoQA.service.state.busy);
  await page.screenshot({path:`${output}/${viewport.width}-preview.png`});
  const fit=await page.locator('dialog').evaluate(n=>({width:n.getBoundingClientRect().width,scroll:n.scrollWidth,client:n.clientWidth}));if(fit.width>viewport.width||fit.scroll>fit.client)throw Error('Dialog overflow');
  await page.getByRole('button',{name:'使用这个形象',exact:true}).click();
  const applied=await page.evaluate(()=>({id:photoQA.applied?.id,neck:photoQA.applied?.frames[0].neck,mirror:photoQA.applied?.frames[0].mirrorX,calls:photoQA.generationCalls,bytes:photoQA.applied?.bytes}));
  if(!applied.id||applied.neck[0]!==beforeNeck||applied.calls!==1||applied.bytes>200000)throw Error('Applied head mismatch');
  // Reopen from the shared picker, choose saved item, and ensure selection survives rebuilding.
  await page.getByRole('button',{name:'用我的照片生成',exact:true}).click();await page.getByText('免费次数已用完',{exact:true}).waitFor();
  if(await page.getByRole('button',{name:'选照片',exact:true}).getAttribute('aria-current')!=='step')throw Error('Reopening skipped photo selection');
  const thumbnail=page.locator('.photo-head-library-avatar img');await thumbnail.waitFor();
  if(!await thumbnail.evaluate(n=>n.complete&&n.naturalWidth===96&&n.src.startsWith('data:image/webp')))throw Error('Missing independent front thumbnail');
  await page.screenshot({path:`${output}/${viewport.width}-library.png`});
  await page.getByRole('button',{name:'校准这个形象',exact:true}).click();
  await page.getByRole('button',{name:'使用这个形象',exact:true}).waitFor({state:'visible'});
  if(await page.getByRole('button',{name:'校准',exact:true}).getAttribute('aria-current')!=='step')throw Error('Library pick did not open align');
  if(!await page.getByRole('button',{name:'使用这个形象',exact:true}).isDisabled())throw Error('Library pick must require four-direction confirm before use');
  for(let i=0;i<4;i++)await page.getByRole('button',{name:i===3?'完成四向校准':'校准，下一个',exact:true}).click();
  await page.waitForFunction(()=>!photoQA.service.state.busy);
  await page.getByRole('button',{name:'使用这个形象',exact:true}).click();
  if(!await page.evaluate(()=>photoQA.draft.customHead?.id===photoQA.applied.id))throw Error('Picker did not receive custom head');
  await page.getByRole('button',{name:'用我的照片生成',exact:true}).click();
  await page.getByRole('button',{name:'校准这个形象',exact:true}).click();
  await page.getByRole('button',{name:'关闭照片生成形象',exact:true}).click();
  await page.getByRole('button',{name:'用我的照片生成',exact:true}).click();
  await page.getByRole('button',{name:'删除这个形象',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('.photo-head-library-card'));
  if(!await page.evaluate(()=>photoQA.draft.customHead?.id===photoQA.applied.id))throw Error('Deleting history broke the worn head');
  await page.getByRole('button',{name:'关闭照片生成形象',exact:true}).click();
  // Closed verification gate still permits local editing and never invokes provider.
  await page.goto(url+'/tests/fixtures/photo-head.html?assets=local&disabled');await page.waitForFunction(()=>document.documentElement.dataset.fixtureReady==='1');
  await page.getByRole('button',{name:'打开照片形象',exact:true}).click();await page.getByText('免费体验1次',{exact:true}).waitFor();
  await page.locator('input[type=file]').setInputFiles('assets/hero-preview/head-elf-boy.webp');await page.locator('.photo-head-crop').waitFor({state:'visible'});
  if(!await page.getByRole('button',{name:'下一步：变身',exact:true}).isDisabled()||await page.evaluate(()=>photoQA.generationCalls!==0))throw Error('Unverified generation was not blocked');
  await page.screenshot({path:`${output}/${viewport.width}-disabled.png`});
  await page.getByRole('button',{name:'关闭照片生成形象',exact:true}).click();
  // Exercise the production lazy facade inside a real parent detail window.
  await page.evaluate(async()=>{
   const [{DetailDialog},{createPhotoHeadFeature},{createHeroPicker}]=await Promise.all([import('/js/view_detail_dialog.js'),import('/js/photo_head_feature.js'),import('/js/view_hero_picker.js')]);
   const el=(tag,cls='',...children)=>{const n=document.createElement(tag);n.className=cls;n.append(...children);return n;};
   const parent=new DetailDialog(document.body,{el,title:'修改名字和形象',className:'equipment-item-dialog hero-customize-dialog'});
   let attempts=0;
   photoQA.assets.photoHeads=createPhotoHeadFeature({assets:photoQA.assets,getOwner:()=>null,onLogin:()=>{},loadService:async()=>{if(++attempts===1)throw Error('Simulated module failure');return import('/js/photo_head_service.js');}});
   parent.body.append(createHeroPicker(photoQA.assets,photoQA.draft));parent.open();
  });
  const parent=page.getByRole('dialog',{name:'修改名字和形象',exact:true}),entry=parent.getByRole('button',{name:'用我的照片生成',exact:true});
  const layout=await parent.evaluate(n=>{const card=n.querySelector('.avatar-option').getBoundingClientRect(),button=n.querySelector('.avatar-photo-entry').getBoundingClientRect();return {below:button.top>=card.bottom,height:button.height,overflow:n.scrollWidth>n.clientWidth};});
  if(!layout.below||layout.height>80||layout.overflow)throw Error('Photo entry must be a compact separate row');
  await entry.click();await page.getByText('形象窗口打开失败，请重试',{exact:true}).waitFor();
  await page.getByRole('button',{name:'重试',exact:true}).click();await page.locator('.photo-head-dialog input[type=file]').waitFor({state:'attached'});
  if(await page.locator('dialog[open]').count()!==2)throw Error('Photo popup did not preserve its parent');
  await page.screenshot({path:`${output}/${viewport.width}-nested-popup.png`});
  await page.keyboard.press('Escape');await page.locator('.photo-head-dialog').waitFor({state:'detached'});
  if(!await parent.isVisible()||!await entry.evaluate(n=>n===document.activeElement))throw Error('Closing photo popup lost parent or focus');
  if(await entry.textContent()!=='用我的照片生成')throw Error('Error changed the entry label');
  await page.screenshot({path:`${output}/${viewport.width}-popup-entry.png`});
  await page.goto(url+'/tests/fixtures/photo-head.html?assets=local&en&vip');await page.waitForFunction(()=>document.documentElement.dataset.fixtureReady==='1');
  await page.locator('#open').click();await page.getByText('Unlimited · Member',{exact:true}).waitFor();
  await page.screenshot({path:`${output}/${viewport.width}-english-empty.png`});
  await page.locator('input[type=file]').setInputFiles('assets/hero-preview/head-elf-boy.webp');await page.locator('.photo-head-crop').waitFor({state:'visible'});
  if(await page.locator('.photo-head-dialog').evaluate(n=>n.scrollWidth>n.clientWidth))throw Error('English dialog overflow');
  await page.screenshot({path:`${output}/${viewport.width}-english-crop.png`});
  report.rows.push({viewport,fit,applied});await context.close();
 }
 if(report.errors.length)throw Error(report.errors.join('\n'));
}finally{fs.writeFileSync(`${output}/report.json`,JSON.stringify(report,null,2));await browser.close();}
console.log(JSON.stringify(report,null,2));
