import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export function officialCatalog(){
 const read=p=>JSON.parse(fs.readFileSync(path.join(root,'data',p+'.json'),'utf8'));
 const cards=read('kids/cards'), effects=read('adventure/spell-effects'), art=read('adventure/skill-art');
 const preferred=['Fire_SingleAttackWithDOT_Level3','Ice_SingleAttack_Level3','Storm_SingleAttack_Level3','Life_SingleAttack_Level3','Death_SingleAttack_Level3'];
 const seen=new Set(),keys=[...preferred,...Object.keys(cards)].filter(key=>{const card=cards[key],ref=effects.cards[key];if(!['fire','ice','storm','life','death'].includes(card.spellSchool)||!ref||!art.bases[ref.base]||seen.has(ref.base)||/^(Pass|Dead|PickPet|HoT|DoT|Fizzle)$/.test(card.type))return false;seen.add(ref.base);return true;});
 const bases=keys.map(k=>effects.cards[k].base),pick=(o,ids)=>Object.fromEntries(ids.map(k=>[k,o[k]]));
 const sheets=[...new Set(bases.flatMap(b=>[art.bases[b].atlas,art.bases[b].effectAtlas].filter(Boolean)))];
 const quests=read('adventure/quest-catalog').quests;
 const petData=read('adventure/pets').pets,mountData=read('adventure/mount-catalog');
 for(const sheet of [...Object.values(mountData.sheets),...mountData.mounts.map(m=>m.art)])if(sheet?.local?.startsWith('assets/'))sheet.local='demos/mount-lab/'+sheet.local;
 const translations=Object.fromEntries(fs.readFileSync(path.join(root,'data/adventure/locale/en.txt'),'utf8').split(/\r?\n/).filter(line=>line.includes('||')).map(line=>line.split('||')));
 const mountEnglish=['Ostrich','Mouse','Ox','Tiger','Rabbit','Dragon','Snake','Horse','Goat','Monkey','Rooster','Dog','Pig','Charging Elephant','Wizard’s Broom','Magic Carpet','Golden Horn Lizard Dragon','Golden Pegasus','Shadow Steed','Royal Gold Dragon (Collector)','Heroic Silver Dragon (Collector)','Tyrant Tiger','Heroic White Dragon (Collector)','Royal Jade Dragon (Collector)','Blazing Phoenix (Collector)','Moon Rabbit','Nightfang Wolf','Windrider Eagle (Collector)','Blueblood Phoenix (Collector)','Little White Eagle','Christmas Reindeer','Little Black Eagle','Steam Robot','Mechanical Spider','Heroic White Dragon','Blueblood Phoenix','Heroic Silver Dragon','Royal Gold Dragon','Royal Jade Dragon','Blazing Phoenix','Primal Crystal Dragon','Earth Turtle','Ocean Turtle','Wings of Hope','Wings of Courage','Blue Crystal Turtle','Dream Dolphin','Mechanical Shark','Enchanted Pumpkin Carriage','Ruby Sky Dragon','Azure Frost Dragon','Bronze Sky Dragon','Jade Primal Dragon','Amethyst Wing Dragon','Little Mammoth','Silver Mammoth','Golden Mammoth','Magic Fox','Christmas Reindeer (31 days)','Golden Fairy Wings','Blue Fairy Wings','White Fairy Wings','Dream Whale','Dreamweaver Fox','Juno’s Snowmobile','Cuddle Dragon','Jade Dragon','Golden Chocobo','Crimson Convertible','Starry Carpet'];
 // IDs, rather than source order, keep translations stable when the catalogue grows.
 const mountIds=['16032','16033','16034','16035','16036','16037','16038','16039','16040','16041','16042','16043','16044','16051','16058','16059','16066','16067','16068','16069','16070','16071','16072','16073','16075','16074','16076','16077','16078','16079','16080','16081','16082','16083','16090','16091','16092','16093','16096','16097','16101','16108','16109','16110','16111','16114','16115','16118','16120','16123','16124','16125','16126','16127','16139','16140','16141','16142','16143','16144','16145','16146','16147','16148','16149','10001','dragon','bird','car','carpet'];
 const mountNames=Object.fromEntries(mountIds.map((id,i)=>[id.length===5?'original-'+id:id,mountEnglish[i]]));
 const companions={sheets:mountData.sheets,mounts:mountData.mounts.map(m=>({...pick(m,['id','name','ground','lift','bob','directions','art','rideable']),nameEn:translations[m.name]||mountNames[m.id]||m.name})),pets:Object.values(petData).map(p=>({id:p.id,name:p.name,nameEn:translations[p.name]||p.name,school:p.school,art:pick(p.art,['cdn','local','rows','cols'])}))};
 const cardNames=Object.fromEntries(keys.map(key=>[key,{zh:effects.cards[key].name,en:translations[effects.cards[key].name]||key.replaceAll('_',' ')}]));
 return {version:1,companions,cardNames,stats:{mounts:mountData.mounts.length,rideableMounts:mountData.mounts.filter(m=>m.rideable).length,cards:Object.keys(cards).length,items:Object.keys(read('adventure/shop-candidates')).length,quests:quests.length,activeQuests:quests.filter(q=>!q.obsolete).length,pets:Object.keys(read('adventure/pets').pets).length,effects:Object.keys(effects.bases).length,courses:read('adventure/language-courses').courses.length},map:read('adventure/world-map-art'),pet:read('adventure/pets').pets.dragon_green.art,cards:pick(cards,keys),effects:{...effects,cards:pick(effects.cards,keys),bases:pick(effects.bases,bases)},art:{...art,bases:pick(art.bases,bases),sheets:pick(art.sheets,sheets)},frames:read('adventure/card-frames')};
}
export function prepareOfficialCatalog(){const text=JSON.stringify(officialCatalog());fs.writeFileSync(path.join(root,'data/official-website.json'),text+'\n');return text;}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))prepareOfficialCatalog();
