import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
export const root=fileURLToPath(new URL('../',import.meta.url));
export const read=file=>JSON.parse(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'));
export function readIslandPacks(){
    const index=read('data/adventure/island-packs/index.json');
    if(index.version!==1||new Set(index.packs.map(p=>p.id)).size!==index.packs.length)throw Error('岛屿扩展索引无效');
    return index.packs.filter(p=>p.enabled).map(row=>{const pack=read(row.file);if(pack.island.id!==row.id)throw Error('岛屿包标识不匹配');return {...pack,mapSource:row.mapSource,file:row.file};});
}
// Small pure registry is generated from JSON so island names and travel metadata
// remain editable without hand-editing engine code. --check is part of map checks.
export function prepareIslandRegistry(check=false){
    const packs=readIslandPacks(),file=new URL('../js/island_pack_registry_core.js',import.meta.url);
    const text='// Generated by scripts/prepare_island_packs.mjs. Author source: island-packs/*.json.\nexport const PACK_ISLANDS = '+JSON.stringify(packs.map(p=>p.island),null,2)+';\n';
    if(check){if(!fs.existsSync(file)||fs.readFileSync(file,'utf8').replaceAll('\r\n','\n')!==text)throw Error('岛屿扩展注册表过期');}
    else fs.writeFileSync(file,text);
    const socialFile=new URL('../data/adventure/social.json',import.meta.url),social=read('data/adventure/social.json');
    for(const [id,row] of Object.entries(social.worlds))if(row.islandPack)delete social.worlds[id];
    for(const pack of packs)social.worlds[pack.island.id]={...pack.social,islandPack:true};
    const socialText=JSON.stringify(social,null,2)+'\n';
    if(check){if(fs.readFileSync(socialFile,'utf8').replaceAll('\r\n','\n')!==socialText)throw Error('岛屿伙伴配置过期');}
    else fs.writeFileSync(socialFile,socialText);
    return packs;
}
if(process.argv[1]===fileURLToPath(import.meta.url))prepareIslandRegistry(process.argv.includes('--check'));
