// Offline, inspectable source/layout comparison and WebP contact sheet.
import fs from 'node:fs';
import path from 'node:path';
const args=process.argv.slice(2),option=(key,fallback)=>args.includes(key)?args[args.indexOf(key)+1]:fallback;
const city=JSON.parse(fs.readFileSync(option('--city','data/adventure/earth/cities/shenzhen.json'),'utf8'));
const output=path.resolve(option('--output','.cache/street-qa/report.html'));
const art=JSON.parse(fs.readFileSync('data/adventure/earth/street-art.json','utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const points=ps=>ps.map(p=>`${p.x},${p.y}`).join(' ');
function map(scene,overlay){
    const s=scene.streetscape;
    return `<svg viewBox="0 0 ${scene.map.w} ${scene.map.h}" role="img" aria-label="${overlay?'制作布局':'来源几何'}"><rect width="100%" height="100%" fill="#e9e4d5"/>${s.surfaces.map(p=>`<polygon points="${points(p.points)}" fill="${p.color}"/>`).join('')}${s.roads.map(r=>`<polyline points="${points(r.points)}" fill="none" stroke="${r.kind==='road'?'#8b9295':'#ddd1b6'}" stroke-width="${r.width}"><title>${esc(r.name||r.sourceId)}</title></polyline>`).join('')}${s.objects.filter(o=>o.footprint&&o.sourceId).map(o=>`<polygon points="${points(o.footprint)}" fill="#9c958c" stroke="#685c52" stroke-width="6"><title>${esc(o.sourceId)}</title></polygon>`).join('')}${overlay?s.objects.filter(o=>!o.sourceId).map(o=>`<circle cx="${o.x}" cy="${o.y}" r="24" fill="#b96b2e"><title>${esc(o.id)}</title></circle>`).join('')+scene.npcs.map(n=>`<circle cx="${n.x}" cy="${n.y}" r="38" fill="#1f70b7"/>`).join(''):''}</svg>`;
}
const scenes=city.nodes.filter(n=>n.dungeon.streetscape).map(n=>`<section><h2>${esc(n.name)}</h2><p>${esc(n.dungeon.streetscape.provenance.sourceFile)} · WGS84 · 每米16单位</p><div class="pair"><figure>${map(n.dungeon,false)}<figcaption>来源道路、建筑占地与地表；道路宽度含推定值</figcaption></figure><figure>${map(n.dungeon,true)}<figcaption>同尺度制作布局：蓝色为互动居民，橙色为艺术补全</figcaption></figure></div><a href="http://127.0.0.1:8794/tests/fixtures/city-dungeons.html?city=${esc(city.id)}&node=${esc(n.id)}">进入隔离预览</a></section>`).join('');
const cards=Object.entries(art.entries).map(([key,a])=>{const resource=a.atlas?art.atlases[a.atlas]:a,src=esc(path.relative(path.dirname(output),path.resolve(resource.local)).replaceAll('\\','/'));const preview=a.crop?`<svg viewBox="${a.crop.join(' ')}" style="height:180px" role="img" aria-label="${esc(key)}"><image href="${src}" width="${resource.width}" height="${resource.height}"/></svg>`:`<img src="${src}" alt="${esc(key)}">`;return`<figure>${preview}<figcaption>${esc(key)} · ${resource.bytes} 字节${a.atlas?'（共享图集）':''}<br><a href="${esc(resource.cdn)}">永久CDN</a></figcaption></figure>`;}).join('');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>城市街景制作对照</title><style>body{margin:32px auto;padding:0 20px;max-width:1200px;background:#f6f3ea;color:#253b38;font:16px/1.6 system-ui}h1,h2{font-weight:600}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0;padding:12px;background:white;border-radius:12px}svg{width:100%}.art{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px}.art img{width:100%;height:180px;object-fit:contain;background:#e0e5d8}a{color:#246b7b}section{margin:32px 0}@media(max-width:600px){.pair{grid-template-columns:1fr}}</style><h1>城市街景 1.0 · 制作对照</h1><p>底图约束道路、建筑占地与岸线；建筑立面、商户名称、人物和绿化为艺术加工。缺失数据不能视为现场不存在。© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors · ODbL</a>。</p>${scenes}<h2>共享透明 WebP · 16 张</h2><div class="art">${cards}</div></html>`;
const livingIntro='<section><h2>华南生活街区 · 随机生成版本3</h2><p>80种新素材，40张分组图集；店名、菜单和告示独立替换。全球随机城市暂用华南艺术样板，已有专属节点保持原样。</p><a href="http://127.0.0.1:8797/tests/fixtures/city-dungeons.html?sample=1&seed=42">进入可走动样板</a></section>';
fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,html.replace('<h2>共享透明 WebP · 16 张</h2>',livingIntro+'<h2>共享街景素材 · '+Object.keys(art.entries).length+' 个帧引用</h2>'));console.log(output);
