import {esc,guard,notice,section} from './dom.js';
import {SCHOOLS,SCHOOL_NAMES} from '../rules/formulas.js';
import {compileCharacter,STAT_FIELDS} from '../rules/character.js';
import {defaultBuild,autoConfigureDeck} from '../data/presets.js';
import {cardCategory,cardDescription,CATEGORY_NAMES} from '../data/card-categories.js';
import {cardIssues} from '../engine/coverage.js';
export function buildView(host,state,onApply) {
  let side=0,slot=0,draft=structuredClone(state.scenario.teams[0][0]),query='',catalog='cards',category='all';
  function render() {
    let compiled,error;
    try{compiled=compileCharacter(draft,state.ruleset);}catch(e){error=e.message;}
    const attrs=compiled?.attributes??{};
    const list=catalog==='cards'?Object.values(state.ruleset.cards).filter(c=>(c.school===draft.school||c.school==='balance')&&(category==='all'||cardCategory(c,state.ruleset)===category)&&`${c.name??''} ${c.key}`.toLowerCase().includes(query.toLowerCase())):Object.values(state.ruleset.items).filter(i=>i.slot>0&&`${i.name} ${i.gsid}`.includes(query));
    host.innerHTML=section('角色与配装','从真实物品构建角色，或使用显式属性快照进行控制变量实验。',`
    <div class="row" style="margin-bottom:20px"><span class="muted">编辑位置</span><select id="build-slot">${state.scenario.teams.flatMap((team,s)=>team.map((u,i)=>`<option value="${s}-${i}" ${s===side&&i===slot?'selected':''}>${s===0?'A':'B'}${i+1} · ${esc(u.name)}</option>`)).join('')}</select><button id="apply-build" class="primary">应用到阵容</button><button id="reset-build">使用该系基准</button></div>
    <div class="two-col"><div class="stack"><div class="panel"><h3>角色档案</h3><div class="form-grid"><label><span class="label">名称</span><input id="build-name" value="${esc(draft.name)}"></label><label><span class="label">魔法学系</span><select id="school">${SCHOOLS.map(s=>`<option value="${s}" ${draft.school===s?'selected':''}>${SCHOOL_NAMES[s]}</option>`).join('')}</select></label><label><span class="label">等级</span><input id="level" type="number" min="1" max="200" value="${draft.level}"></label><label><span class="label">属性模式</span><select id="mode"><option value="snapshot" ${draft.mode==='snapshot'?'selected':''}>最终属性快照</option><option value="equipment" ${draft.mode==='equipment'?'selected':''}>装备计算</option></select></label><label><span class="label">VIP（−1 为无）</span><input id="vip" type="number" min="-1" max="10" value="${draft.vipLevel??-1}"></label></div>
    <div class="divider"></div><h3>战斗属性</h3>${error?`<p class="error-text">${esc(error)}</p>`:''}<div class="form-grid">${[['maxHP','生命值'],['powerPip','超级能量概率'],['damage','本系攻击 %'],['resist','本系抗性 %'],['critical','本系暴击 %'],['outputHeal','治疗加成 %']].map(([key,label])=>{const value=typeof attrs[key]==='object'?attrs[key][draft.school]:attrs[key];return `<label><span class="label">${label}</span><input data-attribute="${key}" type="number" value="${value??0}" ${draft.mode==='equipment'?'readonly':''}></label>`;}).join('')}</div><p style="font-size:11px;margin:15px 0 0">快照与配装互斥；默认预设是实验档位，不代表真实玩家分布。</p></div>
    <div class="panel"><h3>装备与强化</h3><div>${(draft.equipment??[]).map((e,i)=>{const id=typeof e==='number'?e:e.gsid;return `<span class="equipment-chip">${esc(state.ruleset.items[id]?.name??id)} <input type="number" data-addon="${i}" min="0" max="30" value="${e.addonLevel??0}" aria-label="强化等级" style="width:52px"><button data-remove-equip="${i}">×</button></span>`;}).join('')||'<p>切换右侧物品库添加装备。</p>'}</div><div class="divider"></div><label class="label" for="gems">宝石 GSID（逗号分隔）</label><input id="gems" value="${esc((draft.gems??[]).join(','))}" style="width:100%"><details style="margin-top:15px"><summary>属性来源</summary><pre style="white-space:pre-wrap;font-size:10px">${esc(JSON.stringify(compiled?.sources??[],null,2))}</pre></details></div>
    <div class="panel"><div class="row spread"><h3>配卡 · ${draft.deck.length} / ${draft.deckCapacity??Math.max(64,draft.deck.length)} 张</h3><div class="row"><button id="auto-deck">自动配卡 · 含增益/减益</button><button id="clear-deck">清空</button></div></div><div class="form-grid" style="margin-bottom:16px">${[['deckCapacity','卡包容量',64,200],['handSize','手牌容量',8,20],['drawPerRound','每轮补牌上限 N',draft.handSize??8,20]].map(([key,label,fallback,max])=>`<label><span class="label">${label}</span><input data-deck-rule="${key}" type="number" min="1" max="${max}" value="${draft[key]??fallback}"></label>`).join('')}</div><p>每个己方回合从随机牌库补牌，保留未使用手牌，不超过手牌容量。使用或丢弃的卡片不再返回牌库。</p><div class="catalog">${[...new Set(draft.deck)].map(key=>`<div class="catalog-item"><div>${esc(state.ruleset.cards[key]?.name??key)}<small>${CATEGORY_NAMES[cardCategory(state.ruleset.cards[key],state.ruleset)]} · ${esc(key)}</small></div><div class="row"><b>${draft.deck.filter(k=>k===key).length}</b><button data-remove-card="${esc(key)}">−</button><button data-add-card="${esc(key)}">+</button></div></div>`).join('')}</div></div></div>
    <div class="stack"><div class="panel"><div class="row spread"><h3>数据目录</h3><select id="catalog-kind"><option value="cards" ${catalog==='cards'?'selected':''}>卡牌</option><option value="items" ${catalog==='items'?'selected':''}>物品</option></select></div>${catalog==='cards'?`<label class="label" for="card-category">技能分类</label><select id="card-category" style="width:100%;margin-bottom:12px">${Object.entries(CATEGORY_NAMES).map(([key,label])=>`<option value="${key}" ${category===key?'selected':''}>${label}</option>`).join('')}</select>`:''}<input id="catalog-search" placeholder="搜索名称 / ID" value="${esc(query)}" style="width:100%;margin-bottom:12px"><div class="catalog">${list.slice(0,100).map(item=>{const blocked=catalog==='cards'?cardIssues(item,state.ruleset):[];return `<div class="catalog-item"><div>${esc(item.name??item.key)}<small>${esc(catalog==='cards'?`${CATEGORY_NAMES[cardCategory(item,state.ruleset)]} · ${cardDescription(item,state.ruleset)}`:`GSID ${item.gsid} · 槽位 ${item.slot}`)}</small>${blocked.length?`<small class="error-text">${esc(blocked.join('；'))}</small>`:''}</div><button ${blocked.length?'disabled':''} ${catalog==='cards'?`data-add-card="${esc(item.key)}"`:`data-add-equip="${item.gsid}"`}>+</button></div>`;}).join('')}</div><small>显示前 ${Math.min(100,list.length)} / ${list.length} 项</small></div>
    <div class="panel"><h3>高级角色 JSON</h3><p style="font-size:11px">用于完整快照、分系属性与测试夹具。未支持的战宠或符文路径会阻止战斗。</p><textarea id="build-json" class="json-editor">${esc(JSON.stringify(draft,null,2))}</textarea><button id="load-build-json" style="margin-top:10px">读取 JSON 到编辑器</button></div></div></div>`);
    const bind=(selector,callback)=>host.querySelector(selector).onchange=guard(callback);
    bind('#build-slot',e=>{[side,slot]=e.target.value.split('-').map(Number);draft=structuredClone(state.scenario.teams[side][slot]);render();});
    bind('#build-name',e=>{draft.name=e.target.value;});
    bind('#level',e=>{draft.level=Number(e.target.value);render();});
    bind('#vip',e=>{draft.vipLevel=Number(e.target.value);render();});
    bind('#school',e=>{draft.school=e.target.value;render();});
    bind('#mode',e=>{draft.mode=e.target.value;render();});
    bind('#gems',e=>{draft.gems=e.target.value?e.target.value.split(',').map(Number):[];render();});
    host.querySelectorAll('[data-attribute]').forEach(el=>el.onchange=()=>{draft.attributes??={};const key=el.dataset.attribute,value=Number(el.value);draft.attributes[key]=key in STAT_FIELDS?{...(typeof draft.attributes[key]==='object'?draft.attributes[key]:Object.fromEntries([...SCHOOLS,'balance'].map(s=>[s,draft.attributes[key]??0]))),[draft.school]:value}:value;render();});
    if(catalog==='cards')bind('#card-category',e=>{category=e.target.value;render();});
    bind('#catalog-kind',e=>{catalog=e.target.value;query='';render();});
    const search=host.querySelector('#catalog-search');search.oninput=()=>{query=search.value;const pos=search.selectionStart;render();const el=host.querySelector('#catalog-search');el.focus();el.setSelectionRange(pos,pos);};
    host.querySelectorAll('[data-add-card]').forEach(el=>el.onclick=()=>{draft.deck.push(el.dataset.addCard);render();});
    host.querySelectorAll('[data-remove-card]').forEach(el=>el.onclick=()=>{draft.deck.splice(draft.deck.indexOf(el.dataset.removeCard),1);render();});
    host.querySelectorAll('[data-add-equip]').forEach(el=>el.onclick=()=>{draft.equipment??=[];draft.equipment.push({gsid:Number(el.dataset.addEquip),addonLevel:0});draft.mode='equipment';render();});
    host.querySelectorAll('[data-remove-equip]').forEach(el=>el.onclick=()=>{draft.equipment.splice(Number(el.dataset.removeEquip),1);render();});
    host.querySelectorAll('[data-addon]').forEach(el=>el.onchange=()=>{const i=Number(el.dataset.addon);draft.equipment[i]={gsid:typeof draft.equipment[i]==='number'?draft.equipment[i]:draft.equipment[i].gsid,addonLevel:Number(el.value)};render();});
    host.querySelectorAll('[data-deck-rule]').forEach(el=>el.onchange=()=>{draft[el.dataset.deckRule]=Number(el.value);render();});
    host.querySelector('#auto-deck').onclick=guard(()=>{draft=autoConfigureDeck(draft,state.ruleset);render();notice('已生成包含增益/减益的卡组，点击应用到阵容生效');});
    host.querySelector('#clear-deck').onclick=()=>{draft.deck=[];render();};
    host.querySelector('#reset-build').onclick=()=>{draft=defaultBuild(draft.school,state.ruleset);render();};
    host.querySelector('#load-build-json').onclick=guard(()=>{const build=JSON.parse(host.querySelector('#build-json').value);compileCharacter(build,state.ruleset);draft=build;render();});
    host.querySelector('#apply-build').onclick=guard(()=>{compileCharacter(draft,state.ruleset);onApply(side,slot,structuredClone(draft));notice('角色已应用到阵容');});
  }
  render();return ()=>{};
}
