import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as A from '../js/adventure_core.js';
import {heroCustomizeQuote,resolvedHeadId} from '../js/adventure_hero_customize_core.js';
import {installDragonTotemItems} from '../js/adventure_progression_bonuses_core.js';
import {checkedProgress} from '../js/adventure_cloud_core.js';

const content = JSON.parse(fs.readFileSync(new URL('../data/adventure/chapter.json', import.meta.url)));
installDragonTotemItems(content);

test('body changes persist independently and head plus body costs one look change',()=>{
 const save=A.createAdventure(content,{name:'小哈奇',appearance:'boy',headId:'jade-boy',bodyId:'male3'});
 save.inventory[984]=150;
 const patch={type:'customize-hero',name:save.name,appearance:'boy',headId:'jade-boy',bodyId:'male4'};
 assert.equal(heroCustomizeQuote(save,patch).total,50);
 A.applyAction(save,content,patch);assert.equal(save.headId,'jade-boy');assert.equal(save.bodyId,'male4');
 A.applyAction(save,content,{...patch,headId:'elf-boy',bodyId:'male5'});assert.equal(save.inventory[984],50);
 const cloud=checkedProgress(save,content).save;assert.equal(cloud.bodyId,'male5');assert.equal(cloud.headId,'elf-boy');
 const before=JSON.stringify(save);assert.throws(()=>A.applyAction(save,content,{...patch,bodyId:'female2'}),/不一致/);assert.equal(JSON.stringify(save),before);
 A.applyAction(save,content,{...patch,headId:'elf-boy',bodyId:'male'});assert.equal(save.inventory[984],0);assert.equal(save.bodyId,'male');
});

test('renaming and changing the base head charge magic beans only for what changed', () => {
    const save = A.createAdventure(content, {name: '小哈奇', appearance: 'boy'});
    assert.equal(resolvedHeadId(save), 'elf-boy');
    assert.equal(heroCustomizeQuote(save, {name: '小哈奇', appearance: 'boy', headId: 'elf-boy'}).total, 0);
    const unchanged = JSON.stringify(save);
    assert.throws(() => A.applyAction(save, content, {type: 'customize-hero', name: '小哈奇', appearance: 'boy', headId: 'elf-boy'}), /没有变化/);
    assert.equal(JSON.stringify(save), unchanged);
    assert.throws(() => A.applyAction(save, content, {type: 'customize-hero', name: '新名字', appearance: 'boy', headId: 'elf-boy'}), /改名字需要50魔豆/);
    assert.equal(JSON.stringify(save), unchanged);
    save.inventory[984] = 50;
    A.applyAction(save, content, {type: 'customize-hero', name: '新名字', appearance: 'boy', headId: 'elf-boy'});
    assert.equal(save.name, '新名字');
    assert.equal(save.headId, undefined);
    assert.equal(save.inventory[984], 0);
    save.inventory[984] = 50;
    A.applyAction(save, content, {type: 'customize-hero', name: '新名字', appearance: 'girl', headId: 'elf-girl'});
    assert.equal(save.appearance, 'girl');
    assert.equal(save.headId, 'elf-girl');
    assert.equal(save.name, '新名字');
    assert.equal(save.inventory[984], 0);
    save.inventory[984] = 99;
    assert.throws(() => A.applyAction(save, content, {type: 'customize-hero', name: '再改', appearance: 'boy', headId: 'jade-boy'}), /100魔豆/);
    assert.equal(save.name, '新名字');
    assert.equal(save.appearance, 'girl');
    assert.equal(save.inventory[984], 99);
    save.inventory[984] = 100;
    A.applyAction(save, content, {type: 'customize-hero', name: '再改', appearance: 'boy', headId: 'jade-boy'});
    assert.equal(save.name, '再改');
    assert.equal(save.appearance, 'boy');
    assert.equal(save.headId, 'jade-boy');
    assert.equal(save.inventory[984], 0);
    assert.doesNotThrow(() => A.parseSave(JSON.stringify(save), content));
    assert.throws(() => A.applyAction(save, content, {type: 'customize-hero', name: '坏', appearance: 'girl', headId: 'jade-boy'}), /不一致/);
    A.beginEncounter(save, content, 'fire-scout');
    save.inventory[984] = 100;
    const fighting = JSON.stringify(save);
    assert.throws(() => A.applyAction(save, content, {type: 'customize-hero', name: '战中', appearance: 'boy', headId: 'elf-boy'}), /战斗/);
    assert.equal(JSON.stringify(save), fighting);
});
