import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createIslandCompanionNavigation} from '../js/island_companion_navigation.js';
const layout=JSON.parse(fs.readFileSync(new URL('../data/adventure/maps/camp.json',import.meta.url)));
function harness(){const messages=[],timers=new Set(),worker={postMessage:m=>messages.push(m),terminate(){this.terminated=true;}},world={zone:'camp',layout,w:layout.w,h:layout.h,center:layout.spawn,paths:[],trees:[],npcs:[],encounters:[],buildings:[{x:860,y:810,w:160,h:160}]},from={x:740,y:800},to={x:980,y:800},actor={position:{...from},path:[]};const navigation=createIslandCompanionNavigation({workerFactory:()=>worker,setTimer:fn=>{timers.add(fn);return fn;},clearTimer:fn=>timers.delete(fn)});return{navigation,messages,timers,worker,world,from,to,actor,reply(path){worker.onmessage({data:{id:messages.at(-1).id,path}});}};}
test('island pets defer blocked paths, share the scene and reuse pending destinations',()=>{const h=harness(),options=h.navigation.options(h.actor,h.world);assert.equal(options.requestPath(h.from,h.to),null);assert.equal(h.messages.length,2);assert.equal(h.messages[0].type,'scene');assert.deepEqual(h.actor.path,[]);options.requestPath(h.from,{...h.to,x:h.to.x+1});assert.equal(h.messages.length,2);const route=[{x:740,y:600},{x:980,y:600},h.to];h.reply(route);assert.deepEqual(h.actor.path,route);assert.equal(h.actor.repath,.45);assert.equal(h.navigation.stats().pending,0);assert.equal(h.timers.size,0);h.navigation.dispose();});
test('straight movement cancels pending detours, late or changed-world paths cannot move pets',()=>{for(const action of ['straight','moved','geometry','left']){const h=harness();let live=true;const options=h.navigation.options(h.actor,h.world,()=>live);options.requestPath(h.from,h.to);if(action==='straight')assert.deepEqual(options.requestPath(h.from,{...h.from,y:790}),[{...h.from,y:790}]);if(action==='moved')h.actor.position.x+=30;if(action==='geometry')h.world.trees=[];if(action==='left')live=false;h.reply([h.to]);assert.deepEqual(h.actor.path,[]);h.navigation.dispose();}});
test('failed workers release requests and restore legacy fallback options',()=>{const h=harness();h.navigation.options(h.actor,h.world).requestPath(h.from,h.to);h.worker.onerror();assert.equal(h.worker.terminated,true);assert.equal(h.timers.size,0);assert.equal(h.navigation.stats().pending,0);assert.deepEqual(h.navigation.options(h.actor,h.world),{});});
test('Earth, dungeons and unsupported workers retain their existing paths',()=>{const h=harness();for(const flags of [{isEarth:true},{isDungeon:true},{isCityDungeon:true}])assert.deepEqual(h.navigation.options(h.actor,{...h.world,...flags}),{});assert.deepEqual(createIslandCompanionNavigation({workerFactory:null}).options(h.actor,h.world),{});assert.equal(h.messages.length,0);});
test('meeting jobs use the original specialized path and copy only balance settings',async()=>{const h=harness();h.navigation.options(h.actor,h.world,()=>true,true).requestPath(h.from,h.to);assert.equal(h.messages.at(-1).type,'meeting-path');h.reply([h.to]);assert.deepEqual(h.actor.path,[h.to]);const content={balanceParams:{version:'kids'},irrelevant:()=>{}};const task=h.navigation.findMeeting(h.world,[h.from,h.to],[],content);assert.equal(h.messages.at(-1).type,'meeting');assert.deepEqual(h.messages.at(-1).content,{balanceParams:content.balanceParams});const anchor={x:740,y:620};h.worker.onmessage({data:{id:h.messages.at(-1).id,anchor}});assert.deepEqual(await task,anchor);assert.equal(h.timers.size,0);h.navigation.dispose();});
test('meeting jobs discard stale geometry and resolve failure without hanging',async()=>{for(const action of ['geometry','left','failure']){const h=harness();let live=true;const task=h.navigation.findMeeting(h.world,[h.from,h.to],[],{},()=>live);if(action==='failure')h.worker.onerror();else{if(action==='geometry')h.world.buildings=[];else live=false;h.worker.onmessage({data:{id:h.messages.at(-1).id,anchor:h.from}});}assert.equal(await task,null);assert.equal(h.navigation.stats().pending,0);h.navigation.dispose();}});
