import test from 'node:test';
import assert from 'node:assert/strict';
import {createIslandSceneryCache} from '../js/island_scenery_cache.js';
function fixture(limit){const tasks=[],canvases=[],painted=[],drawn=[];const cache=createIslandSceneryCache({limit,paint:(c,o)=>painted.push(o),createCanvas:()=>{const c={width:0,height:0,getContext:()=>({scale(){},translate(){}})};canvases.push(c);return c;},schedule:fn=>{tasks.push(fn);return fn;},cancel:fn=>{const i=tasks.indexOf(fn);if(i>=0)tasks.splice(i,1);},now:()=>0});return{cache,tasks,canvases,painted,drawn,c:{drawImage:(...args)=>drawn.push(args)},flush(){while(tasks.length)tasks.shift()();}};}
const tree=(x,y)=>({kind:'tree',x,y,size:100}),hero={x:1000,y:1000},rect={x:0,y:0,w:1000,h:1000};
test('island batches prepare outside draw and reuse while the camera moves',()=>{const f=fixture(),world={},image={},rows=[tree(100,100),tree(150,110)];f.cache.begin(world,image,1);assert.equal(f.cache.draw(f.c,rows,0,hero,rect),0);assert.equal(f.painted.length,0);f.flush();assert.deepEqual(f.painted,rows);assert.equal(f.cache.draw(f.c,rows,0,hero,{...rect,x:3}),2);assert.equal(f.drawn.length,1);assert.equal(f.canvases.length,1);});
test('actors, hidden trees and trees fading over the player break batches',()=>{for(const middle of [{kind:'hero',x:120,y:105},{...tree(120,105),hidden:true},tree(120,160)]){const f=fixture(),rows=[tree(100,100),middle,tree(150,200)];f.cache.begin({}, {},1);assert.equal(f.cache.draw(f.c,rows,0,{x:120,y:130},rect),0);f.flush();assert.equal(f.painted.length,0);}});
test('atlas arrival, world changes and density changes release queued and live canvases',()=>{const f=fixture(),world={},image={},rows=[tree(100,100),tree(150,110)];f.cache.begin(world,image,1);f.cache.draw(f.c,rows,0,hero,rect);f.flush();f.cache.begin(world,{},1);assert.equal(f.canvases[0].width,0);assert.equal(f.cache.stats().bytes,0);f.cache.draw(f.c,rows,0,hero,rect);f.cache.begin({},image,2);f.flush();assert.equal(f.painted.length,2);assert.equal(f.cache.stats().pending,0);});
test('batch allocations stay within their byte budget',()=>{const f=fixture(160000);f.cache.begin({}, {},1);for(let i=0;i<20;i++){const rows=[tree(100+i,100),tree(150+i,110)];f.cache.draw(f.c,rows,0,hero,rect);f.flush();assert.ok(f.cache.stats().bytes<=160000);}f.cache.clear();assert.equal(f.cache.stats().bytes,0);assert.ok(f.canvases.every(c=>c.width===0));});

test('a full visible working set does not evict and repaint itself every frame',()=>{const f=fixture(90000),world={},image={},a=[tree(100,100),tree(150,110)],b=[tree(300,100),tree(350,110)];for(let frame=0;frame<20;frame++){f.cache.begin(world,image,1);f.cache.draw(f.c,a,0,hero,rect);f.cache.draw(f.c,b,0,hero,rect);f.flush();}assert.equal(f.canvases.length,1);assert.equal(f.painted.length,2);f.cache.clear();});

test('an actor in one depth band cannot shift cache groups in the next band',()=>{const f=fixture(),world={},image={},rows=[tree(100,100),tree(150,110),tree(100,210),tree(150,220)];f.cache.begin(world,image,1);f.cache.draw(f.c,rows,0,hero,rect);f.cache.draw(f.c,rows,2,hero,rect);f.flush();f.cache.begin(world,image,1);const changed=[rows[0],{kind:'hero',x:200,y:105},...rows.slice(1)];assert.equal(f.cache.draw(f.c,changed,3,hero,rect),5);assert.equal(f.canvases.length,2);f.cache.clear();});
