import test from 'node:test';
import assert from 'node:assert/strict';
import {createLearningChatView} from '../js/view_learning_chat.js';
import {setTranslator} from '../js/locale_runtime.js';

test('English UI never translates Chinese teaching text; translation toggle works both ways',async t=>{
    t.mock.timers.enable({apis:['setTimeout']});
    class Node extends EventTarget{
        constructor(tag){super();this.tag=tag;this.children=[];this.dataset={};this.style={};this.hidden=false;this.className='';this.textContent='';this.scrollHeight=100;this.scrollTop=0;this.clientHeight=100;this.classList={toggle(){}};}
        append(...rows){this.children.push(...rows);}
        replaceChildren(...rows){this.children=rows;}
        setAttribute(){}
        focus(){}
        querySelectorAll(selector){const all=this.children.flatMap(n=>[n,...n.querySelectorAll('*')]);return selector==='button'?all.filter(n=>n.tag==='button'):all;}
    }
    const old=globalThis.document;globalThis.document={body:new Node('body'),createElement:tag=>new Node(tag),createElementNS:(_,tag)=>new Node(tag)};
    t.after(()=>{setTranslator(null);if(old===undefined)delete globalThis.document;else globalThis.document=old;});
    setTranslator(s=>s==='你好！'?'Hello!':s==='回答提示'?'Answer hint':s);
    let yesCount=0,noCount=0,mapCalls=0;const spoken=[];
    const noop=()=>{},view=createLearningChatView({mapWords:async lines=>{mapCalls++;return lines.map(row=>[{text:row.text,color:null}]);},free:()=>yesCount++,close:()=>noCount++,start:noop,finish:noop,cancel:noop,hint:noop,chinese:noop,next:noop,help:noop,speak:(...args)=>spoken.push(args),settings:noop,useReward:noop,challenge:noop});
    const state={profile:{name:'导师',role:'居民'},story:{id:'one',title:'入门',context:'',turns:[{hint:'提示',pattern:'Hello.',answer:{en:'Hello!','zh-CN':'你好！'}}]},locale:'zh-CN',showChinese:true,messages:[{role:'npc',text:{en:'Hello!','zh-CN':'你好！'}}],index:0,hintLevel:3,status:'',busy:false,recording:false,done:false};
    const nodes=()=>document.body.querySelectorAll('*');
    const bubbleGloss=()=>nodes().filter(n=>String(n.className).includes('camp-chat-bubble')).flatMap(n=>n.children).filter(n=>n.className==='camp-chat-translation');
    view.render(state);
    assert.equal(nodes().some(n=>n.className==='camp-chat-reward'),false);
    assert.equal(mapCalls,0,'mapping must be explicitly requested');
    const mapButton=nodes().find(n=>n.className==='camp-chat-replay camp-chat-map');
    await mapButton.onclick();assert.equal(mapCalls,1);assert.equal(mapButton.disabled,true);
    await mapButton.onclick();assert.equal(mapCalls,1,'repeated click does not regenerate mapping');
    assert.ok(nodes().filter(n=>n.className==='camp-chat-original').every(n=>n.textContent==='你好！'));
    assert.ok(nodes().some(n=>n.className==='camp-chat-translation'&&n.textContent==='Hello!'));
    const hintBox=nodes().find(n=>n.className==='camp-chat-hint');
    assert.ok(nodes().find(n=>n.className==='camp-chat-log').querySelectorAll('*').includes(hintBox),'reading prompt belongs to the chat history');
    assert.ok(!nodes().find(n=>n.className==='camp-chat-footer').querySelectorAll('*').includes(hintBox),'footer contains controls, not tips');
    assert.equal(hintBox.querySelectorAll('*').filter(n=>n.className==='camp-chat-original').length,1,'identical pattern and answer appear once');
    const sample=hintBox.querySelectorAll('button')[0];assert.equal(sample.className,'camp-chat-sample');assert.equal(sample.children.at(-1).tag,'svg');sample.onclick();assert.deepEqual(spoken.at(-1),['你好！','user']);
    view.render({...state,locale:'en'});
    const lines=hintBox.querySelectorAll('*').filter(n=>n.className==='camp-chat-original');assert.deepEqual(lines.map(n=>n.textContent),['Hello.','Hello!']);
    assert.equal(hintBox.querySelectorAll('button')[0].children[0].textContent,'Hello!');
    const answerMap=hintBox.querySelectorAll('button').find(n=>n.className.includes('camp-chat-map'));
    assert.ok(answerMap,'player answer has the same mapping control');
    const beforeMap=mapCalls;await answerMap.onclick();assert.equal(mapCalls,beforeMap+1);
    view.render({...state,locale:'en'});assert.equal(hintBox.querySelectorAll('button').find(n=>n.className.includes('camp-chat-map')),answerMap,'unchanged render preserves the mapping request and control');
    await answerMap.onclick();assert.equal(mapCalls,beforeMap+1);
    view.render({...state,locale:'en',hintLevel:0});
    assert.equal(hintBox.hidden,false,'collapsed lesson retains the standard answer');
    assert.equal(hintBox.children.length,1,'collapsed hint contains only the spoken answer row');
    const collapsed=hintBox.querySelectorAll('button')[0];
    assert.equal(collapsed.children[0].textContent,'Hello!');collapsed.onclick();
    assert.deepEqual(spoken.at(-1),['Hello!','user']);
    view.render({...state,locale:'en',hintLevel:3});
    assert.ok(hintBox.children.some(n=>n.textContent==='Hello.'));
    assert.ok(hintBox.children.some(n=>n.textContent==='你好！'));
    view.render({...state,locale:'en',hintLevel:0,practice:{qualified:1,phase:'waiting',params:{speechPracticeCount:3},feedback:{accuracy:.5,parts:[{text:'Hello',missing:true},{text:'!',missing:false}]}}});
    assert.ok(hintBox.querySelectorAll('*').some(n=>n.className==='story-speech-missing'&&n.textContent==='Hello'));
    assert.equal(nodes().find(n=>n.className==='story-ring-label').textContent,'33%');
    view.render({...state,done:true});assert.equal(nodes().find(n=>n.className==='story-ring-label').textContent,'100%');
    view.render({...state,busy:true});assert.equal(hintBox.querySelectorAll('button')[0].disabled,true);
    view.render({...state,showChinese:false});
    assert.equal(nodes().filter(n=>n.className==='camp-chat-translation').length,0);
    view.render({...state,locale:'en',showChinese:true});
    assert.ok(nodes().some(n=>n.className==='camp-chat-translation'&&n.textContent==='你好！'));
    view.render({...state,reward:{amount:10,currency:100},messages:[...state.messages,{role:'npc',text:'Next question'}]});
    assert.equal(nodes().filter(n=>n.className==='camp-chat-reward-preview').length,1);
    assert.ok(nodes().some(n=>n.className==='camp-chat-reward-preview'&&n.textContent==='对话奖励：10 奇豆'));
    view.render({...state,reward:{amount:0,currency:100}});
    assert.ok(nodes().some(n=>n.className==='camp-chat-reward-preview'&&n.textContent==='已领取'));
    view.render({...state,reward:{amount:30,currency:17213}});
    assert.ok(nodes().some(n=>n.className==='camp-chat-reward-preview'&&n.textContent==='对话奖励：30 仙豆'));
    view.render({...state,messages:[{role:'user',text:'I like pets.',feedback:'答对了',learningReward:{key:'attack',percent:3,total:7}}]});
    assert.ok(nodes().some(n=>n.className==='camp-chat-answer-feedback'&&n.textContent==='答对了 · 今日：攻击力 +1%'));
    view.render({...state,messages:[{role:'user',text:'I like pets.',feedback:'答对了 · +10 奇豆',learningReward:{key:'hp',percent:1,total:1}}]});
    assert.ok(nodes().some(n=>n.className==='camp-chat-answer-feedback'&&n.textContent==='答对了 · +10 奇豆 · 今日：生命 +1%'));
    const done={...state,done:true,received:10,reward:{currency:100},messages:[{role:'user',text:'Hello',feedback:'答对了 · +10 奇豆'}]};
    view.render(done);
    const chatLog=nodes().find(n=>n.className==='camp-chat-log');
    const choices=chatLog.querySelectorAll('button').filter(n=>['Yes','No'].includes(n.textContent));
    assert.equal(choices.length,2);choices[0].onclick();choices[1].onclick();assert.equal(yesCount,1);assert.equal(noCount,1);
    assert.equal(nodes().some(n=>n.className==='camp-chat-completed-actions'),false);
    assert.equal(nodes().some(n=>n.className==='camp-chat-reward-summary'||n.className==='camp-chat-celebration'),false);
    view.render({...state,done:true,received:10,reward:{amount:10,currency:100},hintLevel:0});
    assert.equal(view.root.hidden,false);
    assert.equal(nodes().find(n=>n.className==='camp-chat-input').hidden,false);
    assert.equal(nodes().find(n=>n.className==='camp-chat-actions').hidden,false);
    assert.ok(nodes().some(n=>n.tag==='button'&&n.textContent==='No'));
    assert.equal(nodes().find(n=>n.tag==='button'&&n.textContent==='发送').disabled,false);
    view.close();
    view.render({...done,received:0});
    view.render({...state,done:true,received:10,reward:{amount:10,currency:100},hintLevel:0});
    assert.equal(view.root.hidden,false);
    assert.equal(nodes().find(n=>n.className==='camp-chat-input').hidden,false);
    assert.equal(nodes().find(n=>n.className==='camp-chat-actions').hidden,false);
    assert.ok(nodes().some(n=>n.tag==='button'&&n.textContent==='No'));
    assert.equal(nodes().find(n=>n.tag==='button'&&n.textContent==='发送').disabled,false);
    view.close();
    view.render({...state,mode:'free',loginRequired:true,ready:false,remaining:null,hintLevel:0});
    assert.equal(nodes().find(n=>n.className==='camp-chat-login').hidden,false);
    assert.equal(nodes().find(n=>n.className==='camp-chat-input').hidden,true);
    assert.equal(nodes().find(n=>n.className==='camp-chat-actions').hidden,true);
    assert.equal(nodes().find(n=>n.className==='camp-chat-progress').textContent,'登录后可使用 AI 对话');
    view.render({...state,mode:'free',ready:true,remaining:2,hintLevel:0,native:'zh-CN',vip:true,messages:[{role:'assistant',text:'你好呀～我是晴川。',translation:'你好呀～我是晴川。'}]});
    assert.equal(bubbleGloss().length,0);
    view.render({...state,mode:'free',ready:true,remaining:2,hintLevel:0,native:'zh-CN',vip:true,messages:[{role:'assistant',text:'Hello! I bake bread.',translation:'你好！我烤面包。'}]});
    assert.ok(bubbleGloss().some(n=>n.textContent==='你好！我烤面包。'));
    const streaming={...state,mode:'free',ready:true,remaining:2,hintLevel:0,native:'zh-CN',vip:true,messages:[{role:'assistant',text:'Hello! I bake bread.',translation:'你好！我烤面包。',streaming:true}]};
    view.render(streaming);assert.equal(bubbleGloss()[0].hidden,true,'native translation waits for the original stream');
    view.render({...streaming,messages:streaming.messages.map(row=>({...row,streaming:false}))});assert.equal(bubbleGloss()[0].hidden,false);
    view.render({...state,mode:'free',ready:true,remaining:2,hintLevel:0});
    assert.equal(nodes().find(n=>n.className==='camp-chat-login').hidden,true);
    assert.equal(nodes().find(n=>n.className==='camp-chat-input').hidden,false);
    view.render({...state,done:true,received:10,reward:{amount:10,currency:100},hintLevel:0});
    assert.equal(view.root.hidden,false);
    assert.equal(nodes().find(n=>n.className==='camp-chat-input').hidden,false);
    assert.equal(nodes().find(n=>n.className==='camp-chat-actions').hidden,false);
    assert.ok(nodes().some(n=>n.tag==='button'&&n.textContent==='No'));
    assert.equal(nodes().find(n=>n.tag==='button'&&n.textContent==='发送').disabled,false);
    view.close();
});
