import {test,expect} from '@playwright/test';
import {rules} from '../fixtures/data.mjs';import {defaultScenario} from '../../js/data/presets.js';import {runBatch,createReport} from '../../js/simulation/runner.js';
test('desktop workflow, persistence and report UI',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/HaqiCombatEmulator.html');await expect(page.locator('#arena')).toBeVisible();
 await page.locator('#step').click();await expect(page.locator('.turn-label strong')).toHaveText('02');
 await page.locator('[data-view=build]').click();await page.locator('#build-name').fill('测试法师');await page.locator('#build-name').dispatchEvent('change');await page.locator('#apply-build').click();await page.locator('#save-project').click();await expect(page.locator('#notice')).toContainText('已保存');await page.reload();await page.locator('[data-view=build]').click();await expect(page.locator('#build-name')).toHaveValue('测试法师');
 await page.locator('#version').selectOption('teen');await expect(page.locator('#data-status')).toContainText('teen');await page.locator('[data-view=battle]').click();await page.locator('#size').selectOption('2');await expect(page.locator('.section-head .pill')).toHaveText('2 vs 2');
 await page.locator('[data-view=experiments]').click();await page.locator('#count').selectOption('1000');await page.locator('#run-experiment').click();await expect(page.locator('#go-ai')).toBeVisible({timeout:90000});await expect(page.locator('main')).toContainText('1,000');
 await page.locator('#sample-replay').click();await expect(page.locator('#replay-position')).toBeVisible();await page.locator('#replay-position').fill('0');await page.locator('#replay-position').dispatchEvent('input');await expect(page.locator('.turn-label strong')).toHaveText('01');await page.locator('#step').click();await expect(page.locator('.turn-label strong')).toHaveText('02');
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});expect(errors).toEqual([]);
});
test('Worker equals Node, cancellation and candidate retesting are isolated',async({page})=>{
 await page.goto('/HaqiCombatEmulator.html');await expect(page.locator('#arena')).toBeVisible();
 const e={schemaVersion:1,count:40,seed:991,population:'fixed',strategy:'tactical',scenario:defaultScenario(rules.kids,2)};
 const result=await page.evaluate(async experiment=>{const {startExperiment}=await import('./js/simulation/pool.js');const {loadRuleset}=await import('./js/data/loader.js');const r=await loadRuleset('kids');return startExperiment(experiment,r,{workers:2}).promise;},e);
 expect(result).toEqual(createReport(e,rules.kids,runBatch(e,rules.kids)));
 const cancelled=await page.evaluate(async experiment=>{const {startExperiment}=await import('./js/simulation/pool.js');const {loadRuleset}=await import('./js/data/loader.js');const r=await loadRuleset('kids');let task;task=startExperiment({...experiment,count:10000},r,{workers:2,onProgress:()=>task.cancel()});return task.promise;},e);expect(cancelled.partial).toBe(true);expect(cancelled.completed).toBeGreaterThan(0);expect(cancelled.completed).toBeLessThan(10000);
 const retest=await page.evaluate(async report=>{const {evaluateCandidates}=await import('./js/ai/evaluate.js');const {loadRuleset}=await import('./js/data/loader.js');const r=await loadRuleset('kids'),key=report.experiment.scenario.teams[0][0].deck[0],before=r.cards[key].params.damage_min;const candidate={schemaVersion:1,baseHash:r.hash,title:'test',changes:[{path:['cards',key,'params','damage_min'],before,value:before-1}]};const out=await evaluateCandidates(report,r,[candidate]);return {completed:out.results[0].paired.completed,heldout:out.results[0].validation.experiment.seed,unchanged:r.cards[key].params.damage_min===before};},result);expect(retest.completed).toBe(40);expect(retest.unchanged).toBe(true);expect(retest.heldout).not.toBe(e.seed);
});
test('mobile layout and AI offline/invalid suggestion feedback',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/HaqiCombatEmulator.html');await expect(page.locator('#arena')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 await page.locator('[data-view=tuning]').click();await page.route('https://cdn.keepwork.com/**',route=>route.abort());await page.locator('#ai-login').click();await expect(page.locator('#notice')).toContainText('加载失败');
 await page.locator('#patch-json').fill('{"schemaVersion":1,"changes":[]}');await page.locator('#validate-patch').click();await expect(page.locator('#notice')).toContainText('无效');
});
test('10,000 browser 4v4 simulations keep the main thread responsive',async({page})=>{
 await page.goto('/HaqiCombatEmulator.html');await expect(page.locator('#arena')).toBeVisible();
 const result=await page.evaluate(async()=>{const {loadRuleset}=await import('./js/data/loader.js');const {defaultScenario}=await import('./js/data/presets.js');const {startExperiment}=await import('./js/simulation/pool.js');const r=await loadRuleset('kids');let ticks=0;const timer=setInterval(()=>ticks++,25);const start=performance.now();const report=await startExperiment({schemaVersion:1,count:10000,seed:20260916,population:'fixed',strategy:'tactical',scenario:defaultScenario(r,4)},r).promise;clearInterval(timer);return {configHash:r.hash,count:report.completed,elapsedMs:performance.now()-start,uiTimerTicks:ticks,heapMB:performance.memory?.usedJSHeapSize/1024/1024,userAgent:navigator.userAgent};});
 const fs=await import('node:fs');fs.writeFileSync('test-results/benchmark-browser.json',JSON.stringify(result,null,2));expect(result.count).toBe(10000);expect(result.uiTimerTicks).toBeGreaterThan(5);expect(result.elapsedMs).toBeLessThan(60000);
});
test('both versions and all sizes match Node in browser and Workers',async({page})=>{
 await page.goto('/HaqiCombatEmulator.html');await expect(page.locator('#arena')).toBeVisible();
 for(const version of ['kids','teen'])for(const size of [1,2,3,4]){
  const e={schemaVersion:1,count:2,seed:713,population:'fixed',strategy:'tactical',scenario:defaultScenario(rules[version],size)};
  const value=await page.evaluate(async({version,e})=>{const {loadRuleset}=await import('./js/data/loader.js');const {runBatch}=await import('./js/simulation/runner.js');const {startExperiment}=await import('./js/simulation/pool.js');const r=await loadRuleset(version);return {browser:runBatch(e,r),worker:(await startExperiment(e,r,{workers:1}).promise).records};},{version,e});
  const expected=runBatch(e,rules[version]);expect(value.browser).toEqual(expected);expect(value.worker).toEqual(expected);
 }
});
test('deck editing, discard controls, cast presentation and status badges',async({page})=>{
 await page.goto('/HaqiCombatEmulator.html');await expect(page.locator('#arena')).toBeVisible();await page.locator('#size').selectOption('1');
 await page.locator('[data-view=build]').click();await page.locator('[data-deck-rule=deckCapacity]').fill('64');await page.locator('[data-deck-rule=deckCapacity]').dispatchEvent('change');await page.locator('[data-deck-rule=handSize]').fill('4');await page.locator('[data-deck-rule=handSize]').dispatchEvent('change');await page.locator('[data-deck-rule=drawPerRound]').fill('4');await page.locator('[data-deck-rule=drawPerRound]').dispatchEvent('change');await page.locator('#apply-build').click();await page.locator('[data-view=battle]').click();await expect(page.locator('.deck-summary')).toContainText('手牌 4 / 4');
 await page.locator('[data-discard]').last().click();await expect(page.locator('.deck-summary')).toContainText('待弃 1');await page.locator('#step').click();await expect(page.locator('.deck-summary')).toContainText('已弃 1');await expect(page.locator('#cast-display')).toContainText('A1');await expect(page.locator('#cast-display')).toContainText('→');
 await page.evaluate(async()=>{const {state}=await import('./js/state.js');state.battle.units[0].charms.push({id:2});state.battle.units[0].stun=1;state.battle.units[0].absorbs.push({amount:345});});await page.locator('[data-unit="0-0"]').click();await expect(page.locator('.effect-badge').first()).toContainText('伤害 +30%');await expect(page.locator('.unit-effects').first()).toContainText('吸收盾 · 剩余 345');await expect(page.locator('.unit-effects').first()).toContainText('眩晕');await page.screenshot({path:'test-results/deck-status.png',fullPage:true});
});
test('support filters and one-click deck configuration retain character stats',async({page})=>{
 await page.goto('/HaqiCombatEmulator.html');await expect(page.locator('#arena')).toBeVisible();await page.locator('#auto-all-decks').click();await page.locator('[data-view=build]').click();await page.locator('#card-category').selectOption('buff');await expect(page.locator('[data-add-card="Ice_IceDamageBlade"]').last()).toBeVisible();await page.locator('#card-category').selectOption('debuff');await expect(page.locator('[data-add-card="Ice_IceDamageTrap"]').last()).toBeVisible();await page.locator('#clear-deck').click();await page.locator('#auto-deck').click();await page.locator('#apply-build').click();
 const result=await page.evaluate(async()=>{const {state}=await import('./js/state.js');const {cardCategory}=await import('./js/data/card-categories.js');return {types:[...new Set(state.scenario.teams[0][0].deck.map(key=>cardCategory(state.ruleset.cards[key],state.ruleset)))],hp:state.scenario.teams[0][0].attributes.maxHP};});expect(result.types).toContain('buff');expect(result.types).toContain('debuff');expect(result.hp).toBe(5000);
});
test('single-card copy cap and two-color mana counts',async({page})=>{
 await page.goto('/HaqiCombatEmulator.html');await expect(page.locator('#arena')).toBeVisible();await page.locator('[data-view=build]').click();await expect(page.locator('[data-deck-rule=deckCapacity]')).toHaveValue('40');
 const key=await page.locator('[data-add-card]').first().getAttribute('data-add-card'),plus=page.locator(`[data-add-card="${key}"]`).first();await plus.click();await plus.click();await expect(plus).toBeDisabled();await expect(page.locator('main')).toContainText('首轮抽中');await page.locator(`[data-remove-card="${key}"]`).click();await expect(plus).toBeEnabled();
 await page.evaluate(async()=>{const {state}=await import('./js/state.js');state.battle.units[0].pips=2;state.battle.units[0].powerPips=3;});await page.locator('[data-view=battle]').click();await expect(page.locator('.pip-normal').first()).toHaveText('● 普通魔力 2');await expect(page.locator('.pip-power').first()).toHaveText('◆ 超级魔力 3');const colors=await page.evaluate(()=>['.pip-normal','.pip-power'].map(s=>getComputedStyle(document.querySelector(s)).color));expect(colors[0]).not.toBe(colors[1]);await page.locator('.energy-summary').first().screenshot({path:'test-results/energy-colors.png'});
});
