// Generated by prepare_city_living_art.py; alpha-trimmed frame dimensions.
export const livingArtDimensions = {
  "living:cream-balcony": {
    "width": 244,
    "height": 376,
    "group": "buildings"
  },
  "living:brick-home": {
    "width": 246,
    "height": 376,
    "group": "buildings"
  },
  "living:blue-walkup": {
    "width": 240,
    "height": 376,
    "group": "buildings"
  },
  "living:stair-apartment": {
    "width": 242,
    "height": 376,
    "group": "buildings"
  },
  "living:laundry-home": {
    "width": 240,
    "height": 376,
    "group": "buildings"
  },
  "living:tank-apartment": {
    "width": 235,
    "height": 376,
    "group": "buildings"
  },
  "living:peach-home": {
    "width": 239,
    "height": 376,
    "group": "buildings"
  },
  "living:corner-home": {
    "width": 252,
    "height": 376,
    "group": "buildings"
  },
  "living:green-shophouse": {
    "width": 266,
    "height": 376,
    "group": "buildings"
  },
  "living:tile-home": {
    "width": 258,
    "height": 376,
    "group": "buildings"
  },
  "living:white-walkup": {
    "width": 258,
    "height": 376,
    "group": "buildings"
  },
  "living:brick-corner": {
    "width": 268,
    "height": 375,
    "group": "buildings"
  },
  "living:breakfast": {
    "width": 337,
    "height": 319,
    "group": "shops"
  },
  "living:noodles": {
    "width": 328,
    "height": 328,
    "group": "shops"
  },
  "living:grocery": {
    "width": 332,
    "height": 319,
    "group": "shops"
  },
  "living:fruit": {
    "width": 331,
    "height": 320,
    "group": "shops"
  },
  "living:repair": {
    "width": 340,
    "height": 309,
    "group": "shops"
  },
  "living:tea": {
    "width": 339,
    "height": 309,
    "group": "shops"
  },
  "living:florist": {
    "width": 341,
    "height": 320,
    "group": "shops"
  },
  "living:restaurant": {
    "width": 342,
    "height": 309,
    "group": "shops"
  },
  "living:bakery": {
    "width": 338,
    "height": 314,
    "group": "shops"
  },
  "living:hardware": {
    "width": 336,
    "height": 322,
    "group": "shops"
  },
  "living:books": {
    "width": 332,
    "height": 312,
    "group": "shops"
  },
  "living:tailor": {
    "width": 332,
    "height": 317,
    "group": "shops"
  },
  "living:wood-bench": {
    "width": 253,
    "height": 158,
    "group": "facilities"
  },
  "living:stone-bench": {
    "width": 250,
    "height": 99,
    "group": "facilities"
  },
  "living:green-lamp": {
    "width": 56,
    "height": 337,
    "group": "facilities"
  },
  "living:gray-lamp": {
    "width": 137,
    "height": 324,
    "group": "facilities"
  },
  "living:sorting-bin": {
    "width": 272,
    "height": 170,
    "group": "facilities"
  },
  "living:manhole": {
    "width": 231,
    "height": 154,
    "group": "facilities"
  },
  "living:drain": {
    "width": 236,
    "height": 115,
    "group": "facilities"
  },
  "living:steps": {
    "width": 252,
    "height": 116,
    "group": "facilities"
  },
  "living:fence": {
    "width": 229,
    "height": 143,
    "group": "facilities"
  },
  "living:bollards": {
    "width": 248,
    "height": 126,
    "group": "facilities"
  },
  "living:direction-sign": {
    "width": 212,
    "height": 265,
    "group": "facilities"
  },
  "living:menu-board": {
    "width": 158,
    "height": 221,
    "group": "facilities"
  },
  "living:notice-board": {
    "width": 269,
    "height": 246,
    "group": "facilities"
  },
  "living:advert-board": {
    "width": 147,
    "height": 255,
    "group": "facilities"
  },
  "living:bus-shelter": {
    "width": 365,
    "height": 213,
    "group": "facilities"
  },
  "living:bike-rack": {
    "width": 254,
    "height": 213,
    "group": "facilities"
  },
  "living:scooter": {
    "width": 153,
    "height": 224,
    "group": "facilities"
  },
  "living:hydrant": {
    "width": 119,
    "height": 209,
    "group": "facilities"
  },
  "living:utility-box": {
    "width": 194,
    "height": 223,
    "group": "facilities"
  },
  "living:cones": {
    "width": 262,
    "height": 155,
    "group": "facilities"
  },
  "living:steamers": {
    "width": 291,
    "height": 279,
    "group": "life"
  },
  "living:fruit-crates": {
    "width": 314,
    "height": 234,
    "group": "life"
  },
  "living:vegetables": {
    "width": 327,
    "height": 265,
    "group": "life"
  },
  "living:drink-crates": {
    "width": 360,
    "height": 254,
    "group": "life"
  },
  "living:cafe-table": {
    "width": 286,
    "height": 218,
    "group": "life"
  },
  "living:dining-table": {
    "width": 339,
    "height": 205,
    "group": "life"
  },
  "living:handcart": {
    "width": 323,
    "height": 237,
    "group": "life"
  },
  "living:baskets": {
    "width": 297,
    "height": 215,
    "group": "life"
  },
  "living:aircon": {
    "width": 318,
    "height": 126,
    "group": "life"
  },
  "living:laundry": {
    "width": 311,
    "height": 187,
    "group": "life"
  },
  "living:awning": {
    "width": 336,
    "height": 144,
    "group": "life"
  },
  "living:banner": {
    "width": 358,
    "height": 150,
    "group": "life"
  },
  "living:door-canopy": {
    "width": 340,
    "height": 186,
    "group": "life"
  },
  "living:shutter": {
    "width": 352,
    "height": 277,
    "group": "life"
  },
  "living:shelf": {
    "width": 283,
    "height": 283,
    "group": "life"
  },
  "living:wall-sign": {
    "width": 301,
    "height": 189,
    "group": "life"
  },
  "living:banyan-pit": {
    "width": 324,
    "height": 376,
    "group": "plants"
  },
  "living:shade-pit": {
    "width": 277,
    "height": 376,
    "group": "plants"
  },
  "living:palm-pit": {
    "width": 228,
    "height": 376,
    "group": "plants"
  },
  "living:bauhinia-pit": {
    "width": 304,
    "height": 376,
    "group": "plants"
  },
  "living:flowerbed": {
    "width": 334,
    "height": 169,
    "group": "plants"
  },
  "living:hedge": {
    "width": 316,
    "height": 163,
    "group": "plants"
  },
  "living:bougainvillea": {
    "width": 245,
    "height": 264,
    "group": "plants"
  },
  "living:home-pots": {
    "width": 365,
    "height": 232,
    "group": "plants"
  },
  "living:banana-planter": {
    "width": 347,
    "height": 328,
    "group": "plants"
  },
  "living:fern-pot": {
    "width": 294,
    "height": 285,
    "group": "plants"
  },
  "living:shrub-pot": {
    "width": 260,
    "height": 289,
    "group": "plants"
  },
  "living:grass-planter": {
    "width": 358,
    "height": 203,
    "group": "plants"
  },
  "living:asphalt": {
    "width": 256,
    "height": 256,
    "group": "ground"
  },
  "living:sidewalk": {
    "width": 256,
    "height": 256,
    "group": "ground"
  },
  "living:pavers": {
    "width": 256,
    "height": 256,
    "group": "ground"
  },
  "living:brick-paving": {
    "width": 256,
    "height": 256,
    "group": "ground"
  },
  "living:concrete": {
    "width": 256,
    "height": 256,
    "group": "ground"
  },
  "living:lawn": {
    "width": 256,
    "height": 256,
    "group": "ground"
  },
  "living:gravel": {
    "width": 256,
    "height": 256,
    "group": "ground"
  },
  "living:cobbles": {
    "width": 256,
    "height": 256,
    "group": "ground"
  },
  "living:courtyard-gate": {
    "width": 333,
    "height": 325,
    "group": "connectors"
  },
  "living:garden-gate": {
    "width": 344,
    "height": 325,
    "group": "connectors"
  },
  "living:service-gate": {
    "width": 322,
    "height": 319,
    "group": "connectors"
  },
  "living:brick-wall": {
    "width": 334,
    "height": 237,
    "group": "connectors"
  },
  "living:alley-roof": {
    "width": 352,
    "height": 284,
    "group": "connectors"
  },
  "living:meter-wall": {
    "width": 362,
    "height": 280,
    "group": "connectors"
  },
  "living:side-door": {
    "width": 317,
    "height": 308,
    "group": "connectors"
  },
  "living:vine-fence": {
    "width": 346,
    "height": 257,
    "group": "connectors"
  },
  "living:water-meters": {
    "width": 271,
    "height": 340,
    "group": "connectors"
  },
  "living:store-shutter": {
    "width": 347,
    "height": 333,
    "group": "connectors"
  },
  "living:fern-wall": {
    "width": 362,
    "height": 314,
    "group": "connectors"
  },
  "living:alley-arch": {
    "width": 341,
    "height": 338,
    "group": "connectors"
  },
  "living:red-stools": {
    "width": 186,
    "height": 251,
    "group": "details"
  },
  "living:newspaper-rack": {
    "width": 188,
    "height": 292,
    "group": "details"
  },
  "living:delivery-boxes": {
    "width": 234,
    "height": 277,
    "group": "details"
  },
  "living:wash-basin": {
    "width": 242,
    "height": 189,
    "group": "details"
  },
  "living:mop-bucket": {
    "width": 146,
    "height": 332,
    "group": "details"
  },
  "living:umbrella-holder": {
    "width": 131,
    "height": 316,
    "group": "details"
  },
  "living:watering-can": {
    "width": 218,
    "height": 211,
    "group": "details"
  },
  "living:wall-fan": {
    "width": 245,
    "height": 298,
    "group": "details"
  },
  "living:broom-rack": {
    "width": 218,
    "height": 285,
    "group": "details"
  },
  "living:shopping-bags": {
    "width": 250,
    "height": 229,
    "group": "details"
  },
  "living:wall-hose": {
    "width": 211,
    "height": 246,
    "group": "details"
  },
  "living:service-sign": {
    "width": 231,
    "height": 267,
    "group": "details"
  },
  "living:paint-cans": {
    "width": 224,
    "height": 200,
    "group": "details"
  },
  "living:mailbox": {
    "width": 172,
    "height": 230,
    "group": "details"
  },
  "living:folded-cart": {
    "width": 204,
    "height": 280,
    "group": "details"
  },
  "living:shoe-rack": {
    "width": 252,
    "height": 188,
    "group": "details"
  },
  "living:laundry-basket": {
    "width": 346,
    "height": 266,
    "group": "home-details"
  },
  "living:courtyard-sink": {
    "width": 294,
    "height": 376,
    "group": "home-details"
  },
  "living:reed-mat": {
    "width": 97,
    "height": 376,
    "group": "home-details"
  },
  "living:hanging-fern": {
    "width": 345,
    "height": 376,
    "group": "home-details"
  },
  "living:water-barrel": {
    "width": 328,
    "height": 376,
    "group": "home-details"
  },
  "living:citrus-pot": {
    "width": 271,
    "height": 376,
    "group": "home-details"
  },
  "living:porch-lamp": {
    "width": 196,
    "height": 352,
    "group": "home-details"
  },
  "living:delivery-cooler": {
    "width": 367,
    "height": 295,
    "group": "home-details"
  }
};
