// Generated by scripts/prepare_island_packs.mjs. Author source: island-packs/*.json.
export const PACK_ISLANDS = [
  {
    "id": "tide",
    "name": "潮汐岛",
    "source": "web-authored:tide",
    "description": "灯塔仍亮着，可旧信袋里藏着一个谁也不敢说的回答。来和我一起找出它。",
    "recommendedLevel": 60
  },
  {
    "id": "float",
    "name": "浮岸岛",
    "source": "web-authored:float",
    "description": "这里有两张不同的地图。它们画的是同一座岛，为什么名字和道路都不同？",
    "recommendedLevel": 70
  },
  {
    "id": "sail",
    "name": "风帆岛",
    "source": "web-authored:sail",
    "description": "庆典前夜，塔里传出了求救声。我们要先听完整，再决定怎样讲这段过去。",
    "recommendedLevel": 80
  }
];
